Implemented normalisation for weights with sum larger than one. Also …
LSSTDESC/qp pull request #185
Opened 2023-08-03 17:35 UTC by BStoelzner

This fixes the normalisation issue in #146

2023-09-11 16:36 UTC, aimalz requested changes
This is good! It just needs one little unit test to be complete.

2023-10-09 15:47 UTC, BStoelzner commented
@aimalz I've added a unit test, but forgot to let you know. Feel free to take a look :)

2023-10-11 18:30 UTC, BStoelzner commented
The conflict should be resolved now.

2023-10-30 15:38 UTC, aimalz approved these changes
Note the to-do item for an additional test to catch the original way the bug cropped up. I can write it later this week and add it to this PR, or we can make an issue to come back to it some other time.

2023-10-30 15:38 UTC, aimalz commented on tests/qp/test_ensemble.py
Ack, sorry, I meant this comment as a suggestion that could be made now or in the future but failed to change the status of the review to approved to actually indicate that, my bad!

2023-10-31 16:38 UTC, merged